///////////////////////////////////////////////////////////
//  Attribute.cs
//  Implementation of the Class Attribute
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DesignPackage {
	public class Attribute {

		public Attribute(){

		}

		~Attribute(){

		}

	}//end Attribute

}//end namespace DesignPackage