///////////////////////////////////////////////////////////
//  ClassDiagram.cs
//  Implementation of the Class ClassDiagram
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public class ClassDiagram : Diagram {

		public DesignPackage.ClassEntity m_ClassEntity;

		public ClassDiagram(){

		}

		~ClassDiagram(){

		}

	}//end ClassDiagram

}//end namespace DesignPackage