///////////////////////////////////////////////////////////
//  Class.cs
//  Implementation of the Class Class
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public class Class : ClassEntity {

		public Class(){

		}

		~Class(){

		}

	}//end Class

}//end namespace DesignPackage