///////////////////////////////////////////////////////////
//  ClassEntity.cs
//  Implementation of the Class ClassEntity
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public abstract class ClassEntity {

		public DesignPackage.Attribute m_Attribute;
		public DesignPackage.Method m_Method;

		public ClassEntity(){

		}

		~ClassEntity(){

		}

	}//end ClassEntity

}//end namespace DesignPackage