///////////////////////////////////////////////////////////
//  Diagram.cs
//  Implementation of the Class Diagram
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DesignPackage {
	public abstract class Diagram {

		public Diagram(){

		}

		~Diagram(){

		}

	}//end Diagram

}//end namespace DesignPackage