///////////////////////////////////////////////////////////
//  Interface.cs
//  Implementation of the Class Interface
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public class Interface : ClassEntity {

		public Interface(){

		}

		~Interface(){

		}

	}//end Interface

}//end namespace DesignPackage