///////////////////////////////////////////////////////////
//  IXmlNode.cs
//  Implementation of the Interface IXmlNode
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 14:46:46
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DesignPackage {
	/// <summary>
	/// Esta interface declara tudo o que é comum entre todos os nós do XML
	/// </summary>
	public interface IXmlNode  {

	}//end IXmlNode

}//end namespace DesignPackage