///////////////////////////////////////////////////////////
//  Method.cs
//  Implementation of the Class Method
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:30
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DesignPackage {
	public class Method {

		public Method(){

		}

		~Method(){

		}

	}//end Method

}//end namespace DesignPackage