///////////////////////////////////////////////////////////
//  Object.cs
//  Implementation of the Class Object
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:30
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public class Object : SequenceEntity {

		public Object(){

		}

		~Object(){

		}

	}//end Object

}//end namespace DesignPackage