///////////////////////////////////////////////////////////
//  Relationship.cs
//  Implementation of the Class Relationship
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:30
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public class Relationship {

		public DesignPackage.ClassEntity m_ClassEntity;

		public Relationship(){

		}

		~Relationship(){

		}

	}//end Relationship

}//end namespace DesignPackage