///////////////////////////////////////////////////////////
//  SequenceDiagram.cs
//  Implementation of the Class SequenceDiagram
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:30
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DesignPackage;
namespace DesignPackage {
	public class SequenceDiagram : Diagram {

		public DesignPackage.SequenceEntity m_SequenceEntity;

		public SequenceDiagram(){

		}

		~SequenceDiagram(){

		}

	}//end SequenceDiagram

}//end namespace DesignPackage