///////////////////////////////////////////////////////////
//  SequenceEntity.cs
//  Implementation of the Class SequenceEntity
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 10:36:30
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DesignPackage {
	public abstract class SequenceEntity {

		public SequenceEntity(){

		}

		~SequenceEntity(){

		}

	}//end SequenceEntity

}//end namespace DesignPackage