///////////////////////////////////////////////////////////
//  Carro.cs
//  Implementation of the Class Carro
//  Generated by Enterprise Architect
//  Created on:      24-fev-2016 13:12:35
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Carro {

	public Combustivel m_Combustivel;

	public Carro(){

	}

	~Carro(){

	}

}//end Carro