///////////////////////////////////////////////////////////
//  Combustivel.cs
//  Implementation of the Class Combustivel
//  Generated by Enterprise Architect
//  Created on:      24-fev-2016 13:12:35
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Combustivel {

	public Combustivel(){

	}

	~Combustivel(){

	}

}//end Combustivel