///////////////////////////////////////////////////////////
//  Aggregation.cs
//  Implementation of the Class Aggregation
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:32
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Aggregation : Relationship {

		public Aggregation(){

		}

		~Aggregation(){

		}

	}//end Aggregation

}//end namespace Core