///////////////////////////////////////////////////////////
//  Realisation.cs
//  Implementation of the Class Realisation
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Realisation : Relationship {

		public Realisation(){

		}

		~Realisation(){

		}

	}//end Realisation

}//end namespace Core