///////////////////////////////////////////////////////////
//  Client.cs
//  Implementation of the Class Client
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 14:01:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThePackage;
namespace ThePackage {
	public class Client {

		public ThePackage.Order m_Order;

		public Client(){

		}

		~Client(){

		}

	}//end Client

}//end namespace ThePackage