///////////////////////////////////////////////////////////
//  Order.cs
//  Implementation of the Class Order
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 14:01:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThePackage;
namespace ThePackage {
	public class Order {
		
		public ThePackage.Product[] m_Product;

		public Order(){
			m_Product = new ThePackage.Product[1];
		}

		~Order(){

		}

	}//end Order

}//end namespace ThePackage