///////////////////////////////////////////////////////////
//  Product.cs
//  Implementation of the Class Product
//  Generated by Enterprise Architect
//  Created on:      02-mar-2016 14:01:29
//  Original author: hercules
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ThePackage {
	public class Product {

		public Product(){

		}

		~Product(){

		}

	}//end Product

}//end namespace ThePackage