/////////////////////////////////////////////////////////////
////  XMI.cs
////  Implementation of the Class XMI
////  Generated by Enterprise Architect
////  Created on:      07-mar-2016 12:02:20
////  Original author: hercules
/////////////////////////////////////////////////////////////

//using System;
//using System.Collections.Generic;
//using System.Text;
//using System.IO;
//using System.Xml;
//using UnityEngine;

//namespace ParserXMI {
//    public class XMI {

//        private String Url { get; set; }
//        private XmlDocument ParserXMI { get; set; }
//        private List<Diagram> Diagrams { get; set; }
//        private List<Element> Elements { get; set; }

//        public XMI(String url){
//            this.Url = url;
//            this.ParserXMI = new XmlDocument();
//            this.ParserXMI.Load(this.Url);
//            this.Diagrams = new List<Diagram>();
//            this.Elements = new List<Element>();

//            if(validationXMI())
//            {
//                readnodes(this.ParserXMI.DocumentElement);
//            }

//            //TESTS

//            //DIAGRAMS
//            //foreach(Diagram d in Diagrams)
//            //{
//            //    Debug.Log(d.Name +" - "+d.Type +" - "+d.Id );
//            //    foreach(Element e in d.Elements)
//            //    {
//            //        Debug.Log(e.Seqno+" - "+e.Subject);
//            //    }
//            //    Debug.Log("\n");
//            //}

//            //ELEMENTS
//            //foreach(Element e in this.Elements)
//            //{
//            //    //Debug.Log(e.Name+" - "+ e.Idref);
//            //    Debug.Log(e.IdPackage +" - "+e.Name);

//            //    if(e.Links.Count > 0)
//            //    {
//            //        foreach(Link l in e.Links)
//            //        {
//            //            Debug.Log("\t"+l.Tag);
//            //        }
//            //    }
//            //}


//        }

//        private bool validationXMI()
//        {
//            XmlNode noderoot = this.ParserXMI.DocumentElement;
//            if (noderoot.Name == "xmi:XMI")
//            {
//                //Console.WriteLine("It is XMI");
//                return true;
//            }
//            else
//            {
//                //Console.WriteLine("It is not XMI");
//                return false;
//            }
//        }

//        private void readnodes(XmlNode tag)
//        {
//            foreach(XmlNode child in tag)
//            {
//                //Debug.Log(child.Name);

//                //read diagrams
//                readDiagrams(child);

//                //read elements (class, associations, lifelines)
//                readElements(child);

//                //read packagedElements
//                readPackagedElements(child);

//                //linking elements and diagrams

//                //recursive
//                readnodes(child);
//            }
//        }

//        private void readDiagrams(XmlNode tag)
//        {
//            if(tag.Name == "diagram")
//            {
//                Diagram d = new Diagram();
//                d.Id = tag.Attributes["xmi:id"].Value;

//                foreach(XmlNode n in tag.ChildNodes)
//                {
//                    if (n.Name == "properties")
//                    {
//                        d.Name = n.Attributes["name"].Value;
//                        d.Type = n.Attributes["type"].Value;
//                    }

//                    if (n.Name == "elements")
//                    {
//                        foreach(XmlNode elementsNode in n.ChildNodes)
//                        {
//                            if(elementsNode.Name == "element")
//                            {
//                                Element e = new Element();

//                                foreach(XmlNode att in elementsNode.Attributes)
//                                {
//                                    if(att.Name == "geometry")
//                                    {
//                                        e.Geometry = elementsNode.Attributes["geometry"].Value;
//                                    }

//                                    if (att.Name == "subject")
//                                    {
//                                        e.Subject = elementsNode.Attributes["subject"].Value;
//                                    }

//                                    if (att.Name == "seqno")
//                                    {
//                                        e.Seqno = elementsNode.Attributes["seqno"].Value;
//                                    }

//                                    if (att.Name == "style")
//                                    {
//                                        e.Style = elementsNode.Attributes["style"].Value;
//                                    }
//                                }
//                                d.Elements.Add(e);
//                            }
//                        }
//                    }
//                }
//                Diagrams.Add(d);
//            }
//        }

//        private void readElements(XmlNode tag)
//        {
//            if (tag.Name == "element" && tag.ParentNode.Name == "elements" && tag.ParentNode.ParentNode.Name == "xmi:Extension")
//            {
//                Element e = new Element();

//                foreach(XmlNode att in tag.Attributes)
//                {
//                    switch(att.Name)
//                    {
//                        case "xmi:idref":
//                            e.Idref = att.Value;
//                            break;

//                        case "xmi:type":
//                            e.Type = att.Value;
//                            break;

//                        case "name":
//                            e.Name = att.Value;
//                            break;

//                        case "scope":
//                            e.Scope = att.Value;
//                            break;

//                        default:
//                            break;
//                    }
//                }

//                foreach(XmlNode n in tag.ChildNodes)
//                {
//                    foreach(XmlNode att in n.Attributes)
//                    {
//                        switch(att.Name)
//                        {
//                            case "package":
//                                e.IdPackage = att.Value;
//                                break;

//                            case "isAbstract":
//                                e.isAbstract = att.Value;
//                                break;

//                            default:
//                                break;
//                        }
//                    }

//                    if(n.Name == "links")
//                    {
//                        foreach(XmlNode l in n.ChildNodes)
//                        {
//                            Link link = new Link();
//                            link.Tag = l.Name;

//                            foreach(XmlNode att in l.Attributes)
//                            {
//                                switch(att.Name)
//                                {
//                                    case "xmi:id":
//                                        link.Id = att.Value;
//                                        break;

//                                    case "start":
//                                        link.Start = att.Value;
//                                        break;

//                                    case "end":
//                                        link.End = att.Value;
//                                        break;

//                                    default:
//                                        break;
//                                }
//                            }
//                            e.Links.Add(link);
//                        }
//                    }
//                }

//                this.Elements.Add(e);
//            }
//        }

//        private void readPackagedElements(XmlNode tag)
//        {
//            if (tag.Name == "packagedElement" && tag.Attributes["xmi:type"].Value == "uml:Package" && tag.ParentNode.Name == "packagedElement" && tag.ParentNode.ParentNode.Name == "uml:Model")
//            {
//                Debug.Log(tag.Name);
//            }
//        }

//        ~XMI(){

//        }

//    }//end XMI

//}//end namespace ParserXMI