///////////////////////////////////////////////////////////
//  Attribute.cs
//  Implementation of the Class Attribute
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 21:48:45
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Core {
	public class Attribute {

		public Attribute(){

		}

		~Attribute(){

		}

	}//end Attribute

}//end namespace Core