///////////////////////////////////////////////////////////
//  Class.cs
//  Implementation of the Class Class
//  Generated by Enterprise Architect
//  Created on:      07-mar-2016 11:56:11
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Class : SoftwareEntity {

		public Core.Object m_Object;

		public Class(){

		}

		~Class(){

		}

	}//end Class

}//end namespace Core