///////////////////////////////////////////////////////////
//  Interface.cs
//  Implementation of the Class Interface
//  Generated by Enterprise Architect
//  Created on:      07-mar-2016 11:56:11
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Interface : SoftwareEntity {

		public Interface(){

		}

		~Interface(){

		}

	}//end Interface

}//end namespace Core