///////////////////////////////////////////////////////////
//  IXmlNode.cs
//  Implementation of the Interface IXmlNode
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:52
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Core {
	/// <summary>
	/// Esta interface contém informações semelhantes aos nós contidos no XML
	/// </summary>
	public interface IXmlNode  {
        //XML atributtes
        string Tag { get; set; }
        string Type { get; set; }
        string Name { get; set; }
        string Id { get; set; }
        string Visibility { get; set; }
        string IdPackage { get; set; }
        string Geometry { get; set; }
        string Subject { get; set; }
        string Seqno { get; set; }
        string Style { get; set; }
        string IsAbstract { get; set; }
        string Start { get; set; }
        string End { get; set; }
        string IdSource { get; set; }
        string IdTarget { get; set; }

	}//end IXmlNode

}//end namespace Core