///////////////////////////////////////////////////////////
//  IXmlNode.cs
//  Implementation of the Interface IXmlNode
//  Generated by Enterprise Architect
//  Created on:      07-mar-2016 11:56:11
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Core {
	/// <summary>
	/// Esta interface contém informações semelhantes aos nós contidos no XML
	/// </summary>
	public interface IXmlNode  {

	}//end IXmlNode

}//end namespace Core