///////////////////////////////////////////////////////////
//  Lifeline.cs
//  Implementation of the Lifeline Lifeline
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core
{
    public class Lifeline : SoftwareEntity
    {

        //public Core.Object m_Object;

        public Lifeline()
        {

        }

        ~Lifeline()
        {

        }

    }//end Class

}//end namespace Core