///////////////////////////////////////////////////////////
//  LogicalEntity.cs
//  Implementation of the Class LogicalEntity
//  Generated by Enterprise Architect
//  Created on:      07-mar-2016 11:56:11
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public abstract class LogicalEntity : IXmlNode {

		public LogicalEntity(){

		}

		~LogicalEntity(){

		}

	}//end LogicalEntity

}//end namespace Core