///////////////////////////////////////////////////////////
//  Loop.cs
//  Implementation of the Class Loop
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:52
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Loop : LogicalEntity {

		public Loop(){

		}

		~Loop(){

		}

	}//end Loop

}//end namespace Core