///////////////////////////////////////////////////////////
//  Method.cs
//  Implementation of the Class Method
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:52
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Core {
	public class Method {

		public Method(){

		}

		~Method(){

		}

	}//end Method

}//end namespace Core