///////////////////////////////////////////////////////////
//  Method.cs
//  Implementation of the Class Method
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Core {
	public class Method : IXmlNode{

		public Method(){

		}

		~Method(){

		}

	}//end Method

}//end namespace Core