///////////////////////////////////////////////////////////
//  Object.cs
//  Implementation of the Class Object
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:52
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Object : Class {

		public Object(){

		}

		~Object(){

		}

	}//end Object

}//end namespace Core