///////////////////////////////////////////////////////////
//  Package.cs
//  Implementation of the Class Package
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 21:48:45
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Package : IXmlNode {

        //public Core.Diagram m_Diagram;
        public List<IXmlNode> ClassDiagrams { get; private set; }
        public List<IXmlNode> SequenceDiagrams { get; private set; }

		public Package(){
            ClassDiagrams = new List<IXmlNode>();
            SequenceDiagrams = new List<IXmlNode>();
		}

		~Package(){

		}

	}//end Package

}//end namespace Core