///////////////////////////////////////////////////////////
//  Package.cs
//  Implementation of the Class Package
//  Generated by Enterprise Architect
//  Created on:      07-mar-2016 11:56:12
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Package : LogicalEntity {

		public Package(){

		}

		~Package(){

		}

	}//end Package

}//end namespace Core