///////////////////////////////////////////////////////////
//  Relationship.cs
//  Implementation of the Class Relationship
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:52
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public class Relationship {

		public Core.SoftwareEntity m_SoftwareEntity;

		public Relationship(){

		}

		~Relationship(){

		}

	}//end Relationship

}//end namespace Core