///////////////////////////////////////////////////////////
//  SoftwareEntity.cs
//  Implementation of the Class SoftwareEntity
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:52
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Core;
namespace Core {
	public abstract class SoftwareEntity : IXmlNode {

        //XML atributtes
        public string Tag { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Id { get; set; }
        public string Visibility { get; set; }
        public string IdPackage { get; set; }
        public string Geometry { get; set; }
        public string Subject { get; set; }
        public string Seqno { get; set; }
        public string Style { get; set; }
        public string IsAbstract { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
        public string IdSource { get; set; }
        public string IdTarget { get; set; }

		public Core.Method m_Method;
		public Core.Attribute m_Attribute;

		public SoftwareEntity(){

		}

		~SoftwareEntity(){

		}

	}//end SoftwareEntity

}//end namespace Core