///////////////////////////////////////////////////////////
//  TheCore.cs
//  Implementation of the Class TheCore
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 21:48:46
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using ParserXMI;
using UnityEngine;

namespace Core {
	public class TheCore {

        public XMI TheXMI;
        public List<Package> Packages { get; private set; }

		public TheCore(string url){
            TheXMI = new XMI(url);
            Packages = new List<Package>();
            AddPacackges();

            foreach(var p in Packages)
            {
                Debug.Log(p.GetType().ToString());
            }
		}

        private void AddPacackges()
        {
            foreach(IXmlNode p in TheXMI.Packages)
            {
                Packages.Add(p as Package);
            }
        }

        private void AddDiagrams()
        {

        }


		~TheCore(){

		}

	}//end TheCore

}//end namespace Core