///////////////////////////////////////////////////////////
//  TheCore.cs
//  Implementation of the Class TheCore
//  Generated by Enterprise Architect
//  Created on:      14-mar-2016 16:07:53
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using ParserXMI;


namespace Core {
	public class TheCore {

        public XMI TheXMI; 

		public TheCore(string url){
            TheXMI = new XMI(url);
		}

		~TheCore(){

		}

	}//end TheCore

}//end namespace Core